/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AudioSpaceMentionedUser } from './AudioSpaceMentionedUser';
import {
    AudioSpaceMentionedUserFromJSON,
    AudioSpaceMentionedUserFromJSONTyped,
    AudioSpaceMentionedUserToJSON,
    AudioSpaceMentionedUserToJSONTyped,
} from './AudioSpaceMentionedUser';
import type { ItemResult } from './ItemResult';
import {
    ItemResultFromJSON,
    ItemResultFromJSONTyped,
    ItemResultToJSON,
    ItemResultToJSONTyped,
} from './ItemResult';
import type { UserResults } from './UserResults';
import {
    UserResultsFromJSON,
    UserResultsFromJSONTyped,
    UserResultsToJSON,
    UserResultsToJSONTyped,
} from './UserResults';

/**
 * 
 * @export
 * @interface AudioSpaceMetadata
 */
export interface AudioSpaceMetadata {
    /**
     * 
     * @type {string}
     * @memberof AudioSpaceMetadata
     */
    restId: string;
    /**
     * 
     * @type {AudioSpaceMetadataStateEnum}
     * @memberof AudioSpaceMetadata
     */
    state: AudioSpaceMetadataStateEnum;
    /**
     * 
     * @type {string}
     * @memberof AudioSpaceMetadata
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof AudioSpaceMetadata
     */
    mediaKey?: string;
    /**
     * 
     * @type {string}
     * @memberof AudioSpaceMetadata
     */
    contentType?: string;
    /**
     * 创建时间戳（毫秒）
     * @type {number}
     * @memberof AudioSpaceMetadata
     */
    createdAt?: number;
    /**
     * 开始时间戳（毫秒）
     * @type {number}
     * @memberof AudioSpaceMetadata
     */
    startedAt?: number;
    /**
     * 结束时间错（可能是 ISO 8601 或时间戳字符串）
     * @type {string}
     * @memberof AudioSpaceMetadata
     */
    endedAt?: string;
    /**
     * 预定开始时间戳（毫秒）
     * @type {number}
     * @memberof AudioSpaceMetadata
     */
    scheduledStart?: number;
    /**
     * 
     * @type {number}
     * @memberof AudioSpaceMetadata
     */
    updatedAt?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AudioSpaceMetadata
     */
    disallowJoin?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AudioSpaceMetadata
     */
    narrowCastSpaceType?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AudioSpaceMetadata
     */
    isEmployeeOnly?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AudioSpaceMetadata
     */
    isLocked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AudioSpaceMetadata
     */
    isMuted?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AudioSpaceMetadata
     */
    isSpaceAvailableForReplay?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AudioSpaceMetadata
     */
    isSpaceAvailableForClipping?: boolean;
    /**
     * 0=开放, 1=仅关注者
     * @type {number}
     * @memberof AudioSpaceMetadata
     */
    conversationControls?: number;
    /**
     * 
     * @type {number}
     * @memberof AudioSpaceMetadata
     */
    maxAdminCapacity?: number;
    /**
     * 
     * @type {number}
     * @memberof AudioSpaceMetadata
     */
    maxGuestSessions?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AudioSpaceMetadata
     */
    noIncognito?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AudioSpaceMetadata
     */
    replayStartTime?: number;
    /**
     * 
     * @type {number}
     * @memberof AudioSpaceMetadata
     */
    totalReplayWatched?: number;
    /**
     * 
     * @type {number}
     * @memberof AudioSpaceMetadata
     */
    totalLiveListeners?: number;
    /**
     * 
     * @type {number}
     * @memberof AudioSpaceMetadata
     */
    replyCount?: number;
    /**
     * 
     * @type {Array<AudioSpaceMentionedUser>}
     * @memberof AudioSpaceMetadata
     */
    mentionedUsers?: Array<AudioSpaceMentionedUser>;
    /**
     * 
     * @type {UserResults}
     * @memberof AudioSpaceMetadata
     */
    creatorResults?: UserResults;
    /**
     * 
     * @type {ItemResult}
     * @memberof AudioSpaceMetadata
     */
    tweetResults?: ItemResult;
}


/**
 * @export
 */
export const AudioSpaceMetadataStateEnum = {
    Running: 'Running',
    Ended: 'Ended',
    NotStarted: 'NotStarted',
    TimedOut: 'TimedOut'
} as const;
export type AudioSpaceMetadataStateEnum = typeof AudioSpaceMetadataStateEnum[keyof typeof AudioSpaceMetadataStateEnum];


/**
 * Check if a given object implements the AudioSpaceMetadata interface.
 */
export function instanceOfAudioSpaceMetadata(value: object): value is AudioSpaceMetadata {
    if (!('restId' in value) || value['restId'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function AudioSpaceMetadataFromJSON(json: any): AudioSpaceMetadata {
    return AudioSpaceMetadataFromJSONTyped(json, false);
}

export function AudioSpaceMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioSpaceMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'restId': json['rest_id'],
        'state': json['state'],
        'title': json['title'] == null ? undefined : json['title'],
        'mediaKey': json['media_key'] == null ? undefined : json['media_key'],
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'startedAt': json['started_at'] == null ? undefined : json['started_at'],
        'endedAt': json['ended_at'] == null ? undefined : json['ended_at'],
        'scheduledStart': json['scheduled_start'] == null ? undefined : json['scheduled_start'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'disallowJoin': json['disallow_join'] == null ? undefined : json['disallow_join'],
        'narrowCastSpaceType': json['narrow_cast_space_type'] == null ? undefined : json['narrow_cast_space_type'],
        'isEmployeeOnly': json['is_employee_only'] == null ? undefined : json['is_employee_only'],
        'isLocked': json['is_locked'] == null ? undefined : json['is_locked'],
        'isMuted': json['is_muted'] == null ? undefined : json['is_muted'],
        'isSpaceAvailableForReplay': json['is_space_available_for_replay'] == null ? undefined : json['is_space_available_for_replay'],
        'isSpaceAvailableForClipping': json['is_space_available_for_clipping'] == null ? undefined : json['is_space_available_for_clipping'],
        'conversationControls': json['conversation_controls'] == null ? undefined : json['conversation_controls'],
        'maxAdminCapacity': json['max_admin_capacity'] == null ? undefined : json['max_admin_capacity'],
        'maxGuestSessions': json['max_guest_sessions'] == null ? undefined : json['max_guest_sessions'],
        'noIncognito': json['no_incognito'] == null ? undefined : json['no_incognito'],
        'replayStartTime': json['replay_start_time'] == null ? undefined : json['replay_start_time'],
        'totalReplayWatched': json['total_replay_watched'] == null ? undefined : json['total_replay_watched'],
        'totalLiveListeners': json['total_live_listeners'] == null ? undefined : json['total_live_listeners'],
        'replyCount': json['reply_count'] == null ? undefined : json['reply_count'],
        'mentionedUsers': json['mentioned_users'] == null ? undefined : ((json['mentioned_users'] as Array<any>).map(AudioSpaceMentionedUserFromJSON)),
        'creatorResults': json['creator_results'] == null ? undefined : UserResultsFromJSON(json['creator_results']),
        'tweetResults': json['tweet_results'] == null ? undefined : ItemResultFromJSON(json['tweet_results']),
    };
}

export function AudioSpaceMetadataToJSON(json: any): AudioSpaceMetadata {
    return AudioSpaceMetadataToJSONTyped(json, false);
}

export function AudioSpaceMetadataToJSONTyped(value?: AudioSpaceMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rest_id': value['restId'],
        'state': value['state'],
        'title': value['title'],
        'media_key': value['mediaKey'],
        'content_type': value['contentType'],
        'created_at': value['createdAt'],
        'started_at': value['startedAt'],
        'ended_at': value['endedAt'],
        'scheduled_start': value['scheduledStart'],
        'updated_at': value['updatedAt'],
        'disallow_join': value['disallowJoin'],
        'narrow_cast_space_type': value['narrowCastSpaceType'],
        'is_employee_only': value['isEmployeeOnly'],
        'is_locked': value['isLocked'],
        'is_muted': value['isMuted'],
        'is_space_available_for_replay': value['isSpaceAvailableForReplay'],
        'is_space_available_for_clipping': value['isSpaceAvailableForClipping'],
        'conversation_controls': value['conversationControls'],
        'max_admin_capacity': value['maxAdminCapacity'],
        'max_guest_sessions': value['maxGuestSessions'],
        'no_incognito': value['noIncognito'],
        'replay_start_time': value['replayStartTime'],
        'total_replay_watched': value['totalReplayWatched'],
        'total_live_listeners': value['totalLiveListeners'],
        'reply_count': value['replyCount'],
        'mentioned_users': value['mentionedUsers'] == null ? undefined : ((value['mentionedUsers'] as Array<any>).map(AudioSpaceMentionedUserToJSON)),
        'creator_results': UserResultsToJSON(value['creatorResults']),
        'tweet_results': ItemResultToJSON(value['tweetResults']),
    };
}

