/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AudioSpaceData } from './AudioSpaceData';
import {
    AudioSpaceDataFromJSON,
    AudioSpaceDataFromJSONTyped,
    AudioSpaceDataToJSON,
    AudioSpaceDataToJSONTyped,
} from './AudioSpaceData';
import type { ErrorResponse } from './ErrorResponse';
import {
    ErrorResponseFromJSON,
    ErrorResponseFromJSONTyped,
    ErrorResponseToJSON,
    ErrorResponseToJSONTyped,
} from './ErrorResponse';

/**
 * 
 * @export
 * @interface AudioSpaceByIdResponse
 */
export interface AudioSpaceByIdResponse {
    /**
     * 
     * @type {AudioSpaceData}
     * @memberof AudioSpaceByIdResponse
     */
    data: AudioSpaceData;
    /**
     * 
     * @type {Array<ErrorResponse>}
     * @memberof AudioSpaceByIdResponse
     */
    errors?: Array<ErrorResponse>;
}

/**
 * Check if a given object implements the AudioSpaceByIdResponse interface.
 */
export function instanceOfAudioSpaceByIdResponse(value: object): value is AudioSpaceByIdResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AudioSpaceByIdResponseFromJSON(json: any): AudioSpaceByIdResponse {
    return AudioSpaceByIdResponseFromJSONTyped(json, false);
}

export function AudioSpaceByIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioSpaceByIdResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AudioSpaceDataFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ErrorResponseFromJSON)),
    };
}

export function AudioSpaceByIdResponseToJSON(json: any): AudioSpaceByIdResponse {
    return AudioSpaceByIdResponseToJSONTyped(json, false);
}

export function AudioSpaceByIdResponseToJSONTyped(value?: AudioSpaceByIdResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AudioSpaceDataToJSON(value['data']),
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ErrorResponseToJSON)),
    };
}

