/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResults } from './UserResults';
import {
    UserResultsFromJSON,
    UserResultsFromJSONTyped,
    UserResultsToJSON,
    UserResultsToJSONTyped,
} from './UserResults';

/**
 * 
 * @export
 * @interface AudioSpaceParticipant
 */
export interface AudioSpaceParticipant {
    /**
     * 
     * @type {string}
     * @memberof AudioSpaceParticipant
     */
    periscopeUserId: string;
    /**
     * 加入时间戳（毫秒）
     * @type {number}
     * @memberof AudioSpaceParticipant
     */
    start?: number;
    /**
     * 
     * @type {string}
     * @memberof AudioSpaceParticipant
     */
    twitterScreenName: string;
    /**
     * 
     * @type {string}
     * @memberof AudioSpaceParticipant
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof AudioSpaceParticipant
     */
    avatarUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AudioSpaceParticipant
     */
    isVerified?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AudioSpaceParticipant
     */
    isMutedByAdmin?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AudioSpaceParticipant
     */
    isMutedByGuest?: boolean;
    /**
     * 
     * @type {UserResults}
     * @memberof AudioSpaceParticipant
     */
    userResults?: UserResults;
}

/**
 * Check if a given object implements the AudioSpaceParticipant interface.
 */
export function instanceOfAudioSpaceParticipant(value: object): value is AudioSpaceParticipant {
    if (!('periscopeUserId' in value) || value['periscopeUserId'] === undefined) return false;
    if (!('twitterScreenName' in value) || value['twitterScreenName'] === undefined) return false;
    return true;
}

export function AudioSpaceParticipantFromJSON(json: any): AudioSpaceParticipant {
    return AudioSpaceParticipantFromJSONTyped(json, false);
}

export function AudioSpaceParticipantFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioSpaceParticipant {
    if (json == null) {
        return json;
    }
    return {
        
        'periscopeUserId': json['periscope_user_id'],
        'start': json['start'] == null ? undefined : json['start'],
        'twitterScreenName': json['twitter_screen_name'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'isVerified': json['is_verified'] == null ? undefined : json['is_verified'],
        'isMutedByAdmin': json['is_muted_by_admin'] == null ? undefined : json['is_muted_by_admin'],
        'isMutedByGuest': json['is_muted_by_guest'] == null ? undefined : json['is_muted_by_guest'],
        'userResults': json['user_results'] == null ? undefined : UserResultsFromJSON(json['user_results']),
    };
}

export function AudioSpaceParticipantToJSON(json: any): AudioSpaceParticipant {
    return AudioSpaceParticipantToJSONTyped(json, false);
}

export function AudioSpaceParticipantToJSONTyped(value?: AudioSpaceParticipant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'periscope_user_id': value['periscopeUserId'],
        'start': value['start'],
        'twitter_screen_name': value['twitterScreenName'],
        'display_name': value['displayName'],
        'avatar_url': value['avatarUrl'],
        'is_verified': value['isVerified'],
        'is_muted_by_admin': value['isMutedByAdmin'],
        'is_muted_by_guest': value['isMutedByGuest'],
        'user_results': UserResultsToJSON(value['userResults']),
    };
}

