/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AudioSpaceParticipant } from './AudioSpaceParticipant';
import {
    AudioSpaceParticipantFromJSON,
    AudioSpaceParticipantFromJSONTyped,
    AudioSpaceParticipantToJSON,
    AudioSpaceParticipantToJSONTyped,
} from './AudioSpaceParticipant';

/**
 * 
 * @export
 * @interface AudioSpaceParticipants
 */
export interface AudioSpaceParticipants {
    /**
     * 
     * @type {number}
     * @memberof AudioSpaceParticipants
     */
    total: number;
    /**
     * 
     * @type {Array<AudioSpaceParticipant>}
     * @memberof AudioSpaceParticipants
     */
    admins?: Array<AudioSpaceParticipant>;
    /**
     * 
     * @type {Array<AudioSpaceParticipant>}
     * @memberof AudioSpaceParticipants
     */
    speakers?: Array<AudioSpaceParticipant>;
    /**
     * 
     * @type {Array<AudioSpaceParticipant>}
     * @memberof AudioSpaceParticipants
     */
    listeners?: Array<AudioSpaceParticipant>;
}

/**
 * Check if a given object implements the AudioSpaceParticipants interface.
 */
export function instanceOfAudioSpaceParticipants(value: object): value is AudioSpaceParticipants {
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function AudioSpaceParticipantsFromJSON(json: any): AudioSpaceParticipants {
    return AudioSpaceParticipantsFromJSONTyped(json, false);
}

export function AudioSpaceParticipantsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioSpaceParticipants {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'admins': json['admins'] == null ? undefined : ((json['admins'] as Array<any>).map(AudioSpaceParticipantFromJSON)),
        'speakers': json['speakers'] == null ? undefined : ((json['speakers'] as Array<any>).map(AudioSpaceParticipantFromJSON)),
        'listeners': json['listeners'] == null ? undefined : ((json['listeners'] as Array<any>).map(AudioSpaceParticipantFromJSON)),
    };
}

export function AudioSpaceParticipantsToJSON(json: any): AudioSpaceParticipants {
    return AudioSpaceParticipantsToJSONTyped(json, false);
}

export function AudioSpaceParticipantsToJSONTyped(value?: AudioSpaceParticipants | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'admins': value['admins'] == null ? undefined : ((value['admins'] as Array<any>).map(AudioSpaceParticipantToJSON)),
        'speakers': value['speakers'] == null ? undefined : ((value['speakers'] as Array<any>).map(AudioSpaceParticipantToJSON)),
        'listeners': value['listeners'] == null ? undefined : ((value['listeners'] as Array<any>).map(AudioSpaceParticipantToJSON)),
    };
}

