/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AudioSpaceParticipants } from './AudioSpaceParticipants';
import {
    AudioSpaceParticipantsFromJSON,
    AudioSpaceParticipantsFromJSONTyped,
    AudioSpaceParticipantsToJSON,
    AudioSpaceParticipantsToJSONTyped,
} from './AudioSpaceParticipants';
import type { AudioSpaceMetadata } from './AudioSpaceMetadata';
import {
    AudioSpaceMetadataFromJSON,
    AudioSpaceMetadataFromJSONTyped,
    AudioSpaceMetadataToJSON,
    AudioSpaceMetadataToJSONTyped,
} from './AudioSpaceMetadata';

/**
 * 
 * @export
 * @interface AudioSpace
 */
export interface AudioSpace {
    /**
     * 
     * @type {boolean}
     * @memberof AudioSpace
     */
    isSubscribed?: boolean;
    /**
     * 
     * @type {AudioSpaceMetadata}
     * @memberof AudioSpace
     */
    metadata: AudioSpaceMetadata;
    /**
     * 
     * @type {AudioSpaceParticipants}
     * @memberof AudioSpace
     */
    participants?: AudioSpaceParticipants;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AudioSpace
     */
    sharings?: { [key: string]: any; };
}

/**
 * Check if a given object implements the AudioSpace interface.
 */
export function instanceOfAudioSpace(value: object): value is AudioSpace {
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function AudioSpaceFromJSON(json: any): AudioSpace {
    return AudioSpaceFromJSONTyped(json, false);
}

export function AudioSpaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioSpace {
    if (json == null) {
        return json;
    }
    return {
        
        'isSubscribed': json['is_subscribed'] == null ? undefined : json['is_subscribed'],
        'metadata': AudioSpaceMetadataFromJSON(json['metadata']),
        'participants': json['participants'] == null ? undefined : AudioSpaceParticipantsFromJSON(json['participants']),
        'sharings': json['sharings'] == null ? undefined : json['sharings'],
    };
}

export function AudioSpaceToJSON(json: any): AudioSpace {
    return AudioSpaceToJSONTyped(json, false);
}

export function AudioSpaceToJSONTyped(value?: AudioSpace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_subscribed': value['isSubscribed'],
        'metadata': AudioSpaceMetadataToJSON(value['metadata']),
        'participants': AudioSpaceParticipantsToJSON(value['participants']),
        'sharings': value['sharings'],
    };
}

