/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AudioSpace } from './AudioSpace';
import {
    AudioSpaceFromJSON,
    AudioSpaceFromJSONTyped,
    AudioSpaceToJSON,
    AudioSpaceToJSONTyped,
} from './AudioSpace';

/**
 * 
 * @export
 * @interface AudioSpaceData
 */
export interface AudioSpaceData {
    /**
     * 
     * @type {AudioSpace}
     * @memberof AudioSpaceData
     */
    audioSpace: AudioSpace;
}

/**
 * Check if a given object implements the AudioSpaceData interface.
 */
export function instanceOfAudioSpaceData(value: object): value is AudioSpaceData {
    if (!('audioSpace' in value) || value['audioSpace'] === undefined) return false;
    return true;
}

export function AudioSpaceDataFromJSON(json: any): AudioSpaceData {
    return AudioSpaceDataFromJSONTyped(json, false);
}

export function AudioSpaceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioSpaceData {
    if (json == null) {
        return json;
    }
    return {
        
        'audioSpace': AudioSpaceFromJSON(json['audioSpace']),
    };
}

export function AudioSpaceDataToJSON(json: any): AudioSpaceData {
    return AudioSpaceDataToJSONTyped(json, false);
}

export function AudioSpaceDataToJSONTyped(value?: AudioSpaceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'audioSpace': AudioSpaceToJSON(value['audioSpace']),
    };
}

