/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AudioSpaceMentionedUser
 */
export interface AudioSpaceMentionedUser {
    /**
     * 
     * @type {string}
     * @memberof AudioSpaceMentionedUser
     */
    restId: string;
}

/**
 * Check if a given object implements the AudioSpaceMentionedUser interface.
 */
export function instanceOfAudioSpaceMentionedUser(value: object): value is AudioSpaceMentionedUser {
    if (!('restId' in value) || value['restId'] === undefined) return false;
    return true;
}

export function AudioSpaceMentionedUserFromJSON(json: any): AudioSpaceMentionedUser {
    return AudioSpaceMentionedUserFromJSONTyped(json, false);
}

export function AudioSpaceMentionedUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioSpaceMentionedUser {
    if (json == null) {
        return json;
    }
    return {
        
        'restId': json['rest_id'],
    };
}

export function AudioSpaceMentionedUserToJSON(json: any): AudioSpaceMentionedUser {
    return AudioSpaceMentionedUserToJSONTyped(json, false);
}

export function AudioSpaceMentionedUserToJSONTyped(value?: AudioSpaceMentionedUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rest_id': value['restId'],
    };
}

