/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BroadcastQueryResponseDataBroadcastResults } from './BroadcastQueryResponseDataBroadcastResults';
import {
    BroadcastQueryResponseDataBroadcastResultsFromJSON,
    BroadcastQueryResponseDataBroadcastResultsFromJSONTyped,
    BroadcastQueryResponseDataBroadcastResultsToJSON,
    BroadcastQueryResponseDataBroadcastResultsToJSONTyped,
} from './BroadcastQueryResponseDataBroadcastResults';
import type { BroadcastGraphQL } from './BroadcastGraphQL';
import {
    BroadcastGraphQLFromJSON,
    BroadcastGraphQLFromJSONTyped,
    BroadcastGraphQLToJSON,
    BroadcastGraphQLToJSONTyped,
} from './BroadcastGraphQL';

/**
 * 
 * @export
 * @interface BroadcastQueryResponseData
 */
export interface BroadcastQueryResponseData {
    /**
     * 
     * @type {BroadcastQueryResponseDataBroadcastResults}
     * @memberof BroadcastQueryResponseData
     */
    broadcastResults?: BroadcastQueryResponseDataBroadcastResults;
    /**
     * 
     * @type {BroadcastGraphQL}
     * @memberof BroadcastQueryResponseData
     */
    broadcast?: BroadcastGraphQL;
}

/**
 * Check if a given object implements the BroadcastQueryResponseData interface.
 */
export function instanceOfBroadcastQueryResponseData(value: object): value is BroadcastQueryResponseData {
    return true;
}

export function BroadcastQueryResponseDataFromJSON(json: any): BroadcastQueryResponseData {
    return BroadcastQueryResponseDataFromJSONTyped(json, false);
}

export function BroadcastQueryResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BroadcastQueryResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'broadcastResults': json['broadcast_results'] == null ? undefined : BroadcastQueryResponseDataBroadcastResultsFromJSON(json['broadcast_results']),
        'broadcast': json['broadcast'] == null ? undefined : BroadcastGraphQLFromJSON(json['broadcast']),
    };
}

export function BroadcastQueryResponseDataToJSON(json: any): BroadcastQueryResponseData {
    return BroadcastQueryResponseDataToJSONTyped(json, false);
}

export function BroadcastQueryResponseDataToJSONTyped(value?: BroadcastQueryResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'broadcast_results': BroadcastQueryResponseDataBroadcastResultsToJSON(value['broadcastResults']),
        'broadcast': BroadcastGraphQLToJSON(value['broadcast']),
    };
}

