/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Broadcast
 */
export interface Broadcast {
    /**
     * 
     * @type {string}
     * @memberof Broadcast
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Broadcast
     */
    state: string;
    /**
     * 
     * @type {string}
     * @memberof Broadcast
     */
    mediaKey: string;
}

/**
 * Check if a given object implements the Broadcast interface.
 */
export function instanceOfBroadcast(value: object): value is Broadcast {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('mediaKey' in value) || value['mediaKey'] === undefined) return false;
    return true;
}

export function BroadcastFromJSON(json: any): Broadcast {
    return BroadcastFromJSONTyped(json, false);
}

export function BroadcastFromJSONTyped(json: any, ignoreDiscriminator: boolean): Broadcast {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'state': json['state'],
        'mediaKey': json['media_key'],
    };
}

export function BroadcastToJSON(json: any): Broadcast {
    return BroadcastToJSONTyped(json, false);
}

export function BroadcastToJSONTyped(value?: Broadcast | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'state': value['state'],
        'media_key': value['mediaKey'],
    };
}

