/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BroadcastGraphQL } from './BroadcastGraphQL';
import {
    BroadcastGraphQLFromJSON,
    BroadcastGraphQLFromJSONTyped,
    BroadcastGraphQLToJSON,
    BroadcastGraphQLToJSONTyped,
} from './BroadcastGraphQL';

/**
 * 
 * @export
 * @interface BroadcastQueryResponseDataBroadcastResults
 */
export interface BroadcastQueryResponseDataBroadcastResults {
    /**
     * 
     * @type {BroadcastGraphQL}
     * @memberof BroadcastQueryResponseDataBroadcastResults
     */
    result?: BroadcastGraphQL;
}

/**
 * Check if a given object implements the BroadcastQueryResponseDataBroadcastResults interface.
 */
export function instanceOfBroadcastQueryResponseDataBroadcastResults(value: object): value is BroadcastQueryResponseDataBroadcastResults {
    return true;
}

export function BroadcastQueryResponseDataBroadcastResultsFromJSON(json: any): BroadcastQueryResponseDataBroadcastResults {
    return BroadcastQueryResponseDataBroadcastResultsFromJSONTyped(json, false);
}

export function BroadcastQueryResponseDataBroadcastResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BroadcastQueryResponseDataBroadcastResults {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : BroadcastGraphQLFromJSON(json['result']),
    };
}

export function BroadcastQueryResponseDataBroadcastResultsToJSON(json: any): BroadcastQueryResponseDataBroadcastResults {
    return BroadcastQueryResponseDataBroadcastResultsToJSONTyped(json, false);
}

export function BroadcastQueryResponseDataBroadcastResultsToJSONTyped(value?: BroadcastQueryResponseDataBroadcastResults | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': BroadcastGraphQLToJSON(value['result']),
    };
}

