/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BroadcastQueryResponseData } from './BroadcastQueryResponseData';
import {
    BroadcastQueryResponseDataFromJSON,
    BroadcastQueryResponseDataFromJSONTyped,
    BroadcastQueryResponseDataToJSON,
    BroadcastQueryResponseDataToJSONTyped,
} from './BroadcastQueryResponseData';
import type { ErrorResponse } from './ErrorResponse';
import {
    ErrorResponseFromJSON,
    ErrorResponseFromJSONTyped,
    ErrorResponseToJSON,
    ErrorResponseToJSONTyped,
} from './ErrorResponse';

/**
 * 
 * @export
 * @interface BroadcastQueryResponse
 */
export interface BroadcastQueryResponse {
    /**
     * 
     * @type {BroadcastQueryResponseData}
     * @memberof BroadcastQueryResponse
     */
    data?: BroadcastQueryResponseData;
    /**
     * 
     * @type {Array<ErrorResponse>}
     * @memberof BroadcastQueryResponse
     */
    errors?: Array<ErrorResponse>;
}

/**
 * Check if a given object implements the BroadcastQueryResponse interface.
 */
export function instanceOfBroadcastQueryResponse(value: object): value is BroadcastQueryResponse {
    return true;
}

export function BroadcastQueryResponseFromJSON(json: any): BroadcastQueryResponse {
    return BroadcastQueryResponseFromJSONTyped(json, false);
}

export function BroadcastQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BroadcastQueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : BroadcastQueryResponseDataFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ErrorResponseFromJSON)),
    };
}

export function BroadcastQueryResponseToJSON(json: any): BroadcastQueryResponse {
    return BroadcastQueryResponseToJSONTyped(json, false);
}

export function BroadcastQueryResponseToJSONTyped(value?: BroadcastQueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': BroadcastQueryResponseDataToJSON(value['data']),
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ErrorResponseToJSON)),
    };
}

