/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PeriscopeUser } from './PeriscopeUser';
import {
    PeriscopeUserFromJSON,
    PeriscopeUserFromJSONTyped,
    PeriscopeUserToJSON,
    PeriscopeUserToJSONTyped,
} from './PeriscopeUser';
import type { BroadcastGraphQLUserResults } from './BroadcastGraphQLUserResults';
import {
    BroadcastGraphQLUserResultsFromJSON,
    BroadcastGraphQLUserResultsFromJSONTyped,
    BroadcastGraphQLUserResultsToJSON,
    BroadcastGraphQLUserResultsToJSONTyped,
} from './BroadcastGraphQLUserResults';

/**
 * 
 * @export
 * @interface BroadcastGraphQL
 */
export interface BroadcastGraphQL {
    /**
     * 
     * @type {boolean}
     * @memberof BroadcastGraphQL
     */
    availableForReplay?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BroadcastGraphQL
     */
    broadcastId?: string;
    /**
     * 
     * @type {number}
     * @memberof BroadcastGraphQL
     */
    cameraRotation?: number;
    /**
     * 
     * @type {number}
     * @memberof BroadcastGraphQL
     */
    chatOption?: number;
    /**
     * 
     * @type {number}
     * @memberof BroadcastGraphQL
     */
    endTime?: number;
    /**
     * 
     * @type {number}
     * @memberof BroadcastGraphQL
     */
    height?: number;
    /**
     * 
     * @type {string}
     * @memberof BroadcastGraphQL
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BroadcastGraphQL
     */
    imageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof BroadcastGraphQL
     */
    imageUrlMedium?: string;
    /**
     * 
     * @type {string}
     * @memberof BroadcastGraphQL
     */
    imageUrlSmall?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BroadcastGraphQL
     */
    isHighLatency?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BroadcastGraphQL
     */
    mediaKey?: string;
    /**
     * 
     * @type {PeriscopeUser}
     * @memberof BroadcastGraphQL
     */
    periscopeUser?: PeriscopeUser;
    /**
     * 
     * @type {number}
     * @memberof BroadcastGraphQL
     */
    pingTime?: number;
    /**
     * 
     * @type {string}
     * @memberof BroadcastGraphQL
     */
    preLiveSlateUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BroadcastGraphQL
     */
    privateChat?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BroadcastGraphQL
     */
    scheduledStartTime?: number;
    /**
     * 
     * @type {string}
     * @memberof BroadcastGraphQL
     */
    source?: string;
    /**
     * 
     * @type {number}
     * @memberof BroadcastGraphQL
     */
    startTime?: number;
    /**
     * 
     * @type {string}
     * @memberof BroadcastGraphQL
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof BroadcastGraphQL
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof BroadcastGraphQL
     */
    totalWatched?: number;
    /**
     * 
     * @type {number}
     * @memberof BroadcastGraphQL
     */
    totalWatching?: number;
    /**
     * 
     * @type {BroadcastGraphQLUserResults}
     * @memberof BroadcastGraphQL
     */
    userResults?: BroadcastGraphQLUserResults;
    /**
     * 
     * @type {Array<number>}
     * @memberof BroadcastGraphQL
     */
    viewCountGraph?: Array<number>;
}

/**
 * Check if a given object implements the BroadcastGraphQL interface.
 */
export function instanceOfBroadcastGraphQL(value: object): value is BroadcastGraphQL {
    return true;
}

export function BroadcastGraphQLFromJSON(json: any): BroadcastGraphQL {
    return BroadcastGraphQLFromJSONTyped(json, false);
}

export function BroadcastGraphQLFromJSONTyped(json: any, ignoreDiscriminator: boolean): BroadcastGraphQL {
    if (json == null) {
        return json;
    }
    return {
        
        'availableForReplay': json['available_for_replay'] == null ? undefined : json['available_for_replay'],
        'broadcastId': json['broadcast_id'] == null ? undefined : json['broadcast_id'],
        'cameraRotation': json['camera_rotation'] == null ? undefined : json['camera_rotation'],
        'chatOption': json['chat_option'] == null ? undefined : json['chat_option'],
        'endTime': json['end_time'] == null ? undefined : json['end_time'],
        'height': json['height'] == null ? undefined : json['height'],
        'id': json['id'] == null ? undefined : json['id'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'imageUrlMedium': json['image_url_medium'] == null ? undefined : json['image_url_medium'],
        'imageUrlSmall': json['image_url_small'] == null ? undefined : json['image_url_small'],
        'isHighLatency': json['is_high_latency'] == null ? undefined : json['is_high_latency'],
        'mediaKey': json['media_key'] == null ? undefined : json['media_key'],
        'periscopeUser': json['periscope_user'] == null ? undefined : PeriscopeUserFromJSON(json['periscope_user']),
        'pingTime': json['ping_time'] == null ? undefined : json['ping_time'],
        'preLiveSlateUrl': json['pre_live_slate_url'] == null ? undefined : json['pre_live_slate_url'],
        'privateChat': json['private_chat'] == null ? undefined : json['private_chat'],
        'scheduledStartTime': json['scheduled_start_time'] == null ? undefined : json['scheduled_start_time'],
        'source': json['source'] == null ? undefined : json['source'],
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
        'state': json['state'] == null ? undefined : json['state'],
        'status': json['status'] == null ? undefined : json['status'],
        'totalWatched': json['total_watched'] == null ? undefined : json['total_watched'],
        'totalWatching': json['total_watching'] == null ? undefined : json['total_watching'],
        'userResults': json['user_results'] == null ? undefined : BroadcastGraphQLUserResultsFromJSON(json['user_results']),
        'viewCountGraph': json['view_count_graph'] == null ? undefined : json['view_count_graph'],
    };
}

export function BroadcastGraphQLToJSON(json: any): BroadcastGraphQL {
    return BroadcastGraphQLToJSONTyped(json, false);
}

export function BroadcastGraphQLToJSONTyped(value?: BroadcastGraphQL | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available_for_replay': value['availableForReplay'],
        'broadcast_id': value['broadcastId'],
        'camera_rotation': value['cameraRotation'],
        'chat_option': value['chatOption'],
        'end_time': value['endTime'],
        'height': value['height'],
        'id': value['id'],
        'image_url': value['imageUrl'],
        'image_url_medium': value['imageUrlMedium'],
        'image_url_small': value['imageUrlSmall'],
        'is_high_latency': value['isHighLatency'],
        'media_key': value['mediaKey'],
        'periscope_user': PeriscopeUserToJSON(value['periscopeUser']),
        'ping_time': value['pingTime'],
        'pre_live_slate_url': value['preLiveSlateUrl'],
        'private_chat': value['privateChat'],
        'scheduled_start_time': value['scheduledStartTime'],
        'source': value['source'],
        'start_time': value['startTime'],
        'state': value['state'],
        'status': value['status'],
        'total_watched': value['totalWatched'],
        'total_watching': value['totalWatching'],
        'user_results': BroadcastGraphQLUserResultsToJSON(value['userResults']),
        'view_count_graph': value['viewCountGraph'],
    };
}

