/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface BroadcastGraphQLUserResults
 */
export interface BroadcastGraphQLUserResults {
    /**
     * 
     * @type {User}
     * @memberof BroadcastGraphQLUserResults
     */
    result?: User;
}

/**
 * Check if a given object implements the BroadcastGraphQLUserResults interface.
 */
export function instanceOfBroadcastGraphQLUserResults(value: object): value is BroadcastGraphQLUserResults {
    return true;
}

export function BroadcastGraphQLUserResultsFromJSON(json: any): BroadcastGraphQLUserResults {
    return BroadcastGraphQLUserResultsFromJSONTyped(json, false);
}

export function BroadcastGraphQLUserResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BroadcastGraphQLUserResults {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : UserFromJSON(json['result']),
    };
}

export function BroadcastGraphQLUserResultsToJSON(json: any): BroadcastGraphQLUserResults {
    return BroadcastGraphQLUserResultsToJSONTyped(json, false);
}

export function BroadcastGraphQLUserResultsToJSONTyped(value?: BroadcastGraphQLUserResults | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': UserToJSON(value['result']),
    };
}

