/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Broadcast } from './Broadcast';
import {
    BroadcastFromJSON,
    BroadcastFromJSONTyped,
    BroadcastToJSON,
    BroadcastToJSONTyped,
} from './Broadcast';

/**
 * 
 * @export
 * @interface BroadcastsShowResponse
 */
export interface BroadcastsShowResponse {
    /**
     * 
     * @type {{ [key: string]: Broadcast; }}
     * @memberof BroadcastsShowResponse
     */
    broadcasts: { [key: string]: Broadcast; };
}

/**
 * Check if a given object implements the BroadcastsShowResponse interface.
 */
export function instanceOfBroadcastsShowResponse(value: object): value is BroadcastsShowResponse {
    if (!('broadcasts' in value) || value['broadcasts'] === undefined) return false;
    return true;
}

export function BroadcastsShowResponseFromJSON(json: any): BroadcastsShowResponse {
    return BroadcastsShowResponseFromJSONTyped(json, false);
}

export function BroadcastsShowResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BroadcastsShowResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'broadcasts': (mapValues(json['broadcasts'], BroadcastFromJSON)),
    };
}

export function BroadcastsShowResponseToJSON(json: any): BroadcastsShowResponse {
    return BroadcastsShowResponseToJSONTyped(json, false);
}

export function BroadcastsShowResponseToJSONTyped(value?: BroadcastsShowResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'broadcasts': (mapValues(value['broadcasts'], BroadcastToJSON)),
    };
}

