/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, safeArray, safeOptionalArray, safeArrayMap, safeOptionalArrayMap } from '../runtime';
import type { FollowResponseData } from './FollowResponseData';
import {
    FollowResponseDataFromJSON,
    FollowResponseDataFromJSONTyped,
    FollowResponseDataToJSON,
    FollowResponseDataToJSONTyped,
} from './FollowResponseData';
import type { ErrorResponse } from './ErrorResponse';
import {
    ErrorResponseFromJSON,
    ErrorResponseFromJSONTyped,
    ErrorResponseToJSON,
    ErrorResponseToJSONTyped,
} from './ErrorResponse';

/**
 * 
 * @export
 * @interface FollowResponse
 */
export interface FollowResponse {
    /**
     * 
     * @type {FollowResponseData}
     * @memberof FollowResponse
     */
    data: FollowResponseData;
    /**
     * 
     * @type {Array<ErrorResponse>}
     * @memberof FollowResponse
     */
    errors?: Array<ErrorResponse>;
}

/**
 * Check if a given object implements the FollowResponse interface.
 */
export function instanceOfFollowResponse(value: object): value is FollowResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function FollowResponseFromJSON(json: any): FollowResponse {
    return FollowResponseFromJSONTyped(json, false);
}

export function FollowResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FollowResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': FollowResponseDataFromJSON(json['data']),
        'errors': safeOptionalArrayMap(json['errors'], ErrorResponseFromJSON),
    };
}

export function FollowResponseToJSON(json: any): FollowResponse {
    return FollowResponseToJSONTyped(json, false);
}

export function FollowResponseToJSONTyped(value?: FollowResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': FollowResponseDataToJSON(value['data']),
        'errors': safeOptionalArrayMap(value['errors'], ErrorResponseToJSON),
    };
}

