/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiveVideoStreamSource
 */
export interface LiveVideoStreamSource {
    /**
     * 
     * @type {string}
     * @memberof LiveVideoStreamSource
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof LiveVideoStreamSource
     */
    noRedirectPlaybackUrl: string;
    /**
     * 
     * @type {string}
     * @memberof LiveVideoStreamSource
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof LiveVideoStreamSource
     */
    streamType: string;
}

/**
 * Check if a given object implements the LiveVideoStreamSource interface.
 */
export function instanceOfLiveVideoStreamSource(value: object): value is LiveVideoStreamSource {
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('noRedirectPlaybackUrl' in value) || value['noRedirectPlaybackUrl'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('streamType' in value) || value['streamType'] === undefined) return false;
    return true;
}

export function LiveVideoStreamSourceFromJSON(json: any): LiveVideoStreamSource {
    return LiveVideoStreamSourceFromJSONTyped(json, false);
}

export function LiveVideoStreamSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveVideoStreamSource {
    if (json == null) {
        return json;
    }
    return {
        
        'location': json['location'],
        'noRedirectPlaybackUrl': json['noRedirectPlaybackUrl'],
        'status': json['status'],
        'streamType': json['streamType'],
    };
}

export function LiveVideoStreamSourceToJSON(json: any): LiveVideoStreamSource {
    return LiveVideoStreamSourceToJSONTyped(json, false);
}

export function LiveVideoStreamSourceToJSONTyped(value?: LiveVideoStreamSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'location': value['location'],
        'noRedirectPlaybackUrl': value['noRedirectPlaybackUrl'],
        'status': value['status'],
        'streamType': value['streamType'],
    };
}

