/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LiveVideoStreamSource } from './LiveVideoStreamSource';
import {
    LiveVideoStreamSourceFromJSON,
    LiveVideoStreamSourceFromJSONTyped,
    LiveVideoStreamSourceToJSON,
    LiveVideoStreamSourceToJSONTyped,
} from './LiveVideoStreamSource';

/**
 * 
 * @export
 * @interface LiveVideoStreamStatusResponse
 */
export interface LiveVideoStreamStatusResponse {
    /**
     * 
     * @type {LiveVideoStreamSource}
     * @memberof LiveVideoStreamStatusResponse
     */
    source: LiveVideoStreamSource;
    /**
     * 
     * @type {string}
     * @memberof LiveVideoStreamStatusResponse
     */
    sessionId: string;
    /**
     * 
     * @type {string}
     * @memberof LiveVideoStreamStatusResponse
     */
    chatToken?: string;
    /**
     * 
     * @type {string}
     * @memberof LiveVideoStreamStatusResponse
     */
    lifecycleToken?: string;
    /**
     * 
     * @type {string}
     * @memberof LiveVideoStreamStatusResponse
     */
    shareUrl?: string;
}

/**
 * Check if a given object implements the LiveVideoStreamStatusResponse interface.
 */
export function instanceOfLiveVideoStreamStatusResponse(value: object): value is LiveVideoStreamStatusResponse {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    return true;
}

export function LiveVideoStreamStatusResponseFromJSON(json: any): LiveVideoStreamStatusResponse {
    return LiveVideoStreamStatusResponseFromJSONTyped(json, false);
}

export function LiveVideoStreamStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveVideoStreamStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'source': LiveVideoStreamSourceFromJSON(json['source']),
        'sessionId': json['sessionId'],
        'chatToken': json['chatToken'] == null ? undefined : json['chatToken'],
        'lifecycleToken': json['lifecycleToken'] == null ? undefined : json['lifecycleToken'],
        'shareUrl': json['shareUrl'] == null ? undefined : json['shareUrl'],
    };
}

export function LiveVideoStreamStatusResponseToJSON(json: any): LiveVideoStreamStatusResponse {
    return LiveVideoStreamStatusResponseToJSONTyped(json, false);
}

export function LiveVideoStreamStatusResponseToJSONTyped(value?: LiveVideoStreamStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': LiveVideoStreamSourceToJSON(value['source']),
        'sessionId': value['sessionId'],
        'chatToken': value['chatToken'],
        'lifecycleToken': value['lifecycleToken'],
        'shareUrl': value['shareUrl'],
    };
}

