/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, safeArray, safeOptionalArray, safeArrayMap, safeOptionalArrayMap } from '../runtime';
import type { MediaVideoInfoVariant } from './MediaVideoInfoVariant';
import {
    MediaVideoInfoVariantFromJSON,
    MediaVideoInfoVariantFromJSONTyped,
    MediaVideoInfoVariantToJSON,
    MediaVideoInfoVariantToJSONTyped,
} from './MediaVideoInfoVariant';

/**
 * 
 * @export
 * @interface MediaVideoInfo
 */
export interface MediaVideoInfo {
    /**
     * 
     * @type {Array<number>}
     * @memberof MediaVideoInfo
     */
    aspectRatio: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof MediaVideoInfo
     */
    durationMillis?: number;
    /**
     * 
     * @type {Array<MediaVideoInfoVariant>}
     * @memberof MediaVideoInfo
     */
    variants: Array<MediaVideoInfoVariant>;
}

/**
 * Check if a given object implements the MediaVideoInfo interface.
 */
export function instanceOfMediaVideoInfo(value: object): value is MediaVideoInfo {
    if (!('aspectRatio' in value) || value['aspectRatio'] === undefined) return false;
    if (!('variants' in value) || value['variants'] === undefined) return false;
    return true;
}

export function MediaVideoInfoFromJSON(json: any): MediaVideoInfo {
    return MediaVideoInfoFromJSONTyped(json, false);
}

export function MediaVideoInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaVideoInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'aspectRatio': safeArray(json['aspect_ratio']),
        'durationMillis': json['duration_millis'] == null ? undefined : json['duration_millis'],
        'variants': safeArrayMap(json['variants'], MediaVideoInfoVariantFromJSON),
    };
}

export function MediaVideoInfoToJSON(json: any): MediaVideoInfo {
    return MediaVideoInfoToJSONTyped(json, false);
}

export function MediaVideoInfoToJSONTyped(value?: MediaVideoInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aspect_ratio': safeArray(value['aspectRatio']),
        'duration_millis': value['durationMillis'],
        'variants': safeArrayMap(value['variants'], MediaVideoInfoVariantToJSON),
    };
}

