/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PeriscopeUser
 */
export interface PeriscopeUser {
    /**
     * 
     * @type {string}
     * @memberof PeriscopeUser
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof PeriscopeUser
     */
    profileImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PeriscopeUser
     */
    restId?: string;
    /**
     * 
     * @type {string}
     * @memberof PeriscopeUser
     */
    username?: string;
}

/**
 * Check if a given object implements the PeriscopeUser interface.
 */
export function instanceOfPeriscopeUser(value: object): value is PeriscopeUser {
    return true;
}

export function PeriscopeUserFromJSON(json: any): PeriscopeUser {
    return PeriscopeUserFromJSONTyped(json, false);
}

export function PeriscopeUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PeriscopeUser {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'profileImageUrl': json['profile_image_url'] == null ? undefined : json['profile_image_url'],
        'restId': json['rest_id'] == null ? undefined : json['rest_id'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function PeriscopeUserToJSON(json: any): PeriscopeUser {
    return PeriscopeUserToJSONTyped(json, false);
}

export function PeriscopeUserToJSONTyped(value?: PeriscopeUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['displayName'],
        'profile_image_url': value['profileImageUrl'],
        'rest_id': value['restId'],
        'username': value['username'],
    };
}

