/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, safeArray, safeOptionalArray, safeArrayMap, safeOptionalArrayMap } from '../runtime';
import type { LimitedActionResultsData } from './LimitedActionResultsData';
import {
    LimitedActionResultsDataFromJSON,
    LimitedActionResultsDataFromJSONTyped,
    LimitedActionResultsDataToJSON,
    LimitedActionResultsDataToJSONTyped,
} from './LimitedActionResultsData';

/**
 * 
 * @export
 * @interface TweetLimitedActionResults
 */
export interface TweetLimitedActionResults {
    /**
     * 
     * @type {Array<LimitedActionResultsData>}
     * @memberof TweetLimitedActionResults
     */
    limitedActions: Array<LimitedActionResultsData>;
}

/**
 * Check if a given object implements the TweetLimitedActionResults interface.
 */
export function instanceOfTweetLimitedActionResults(value: object): value is TweetLimitedActionResults {
    if (!('limitedActions' in value) || value['limitedActions'] === undefined) return false;
    return true;
}

export function TweetLimitedActionResultsFromJSON(json: any): TweetLimitedActionResults {
    return TweetLimitedActionResultsFromJSONTyped(json, false);
}

export function TweetLimitedActionResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetLimitedActionResults {
    if (json == null) {
        return json;
    }
    return {
        
        'limitedActions': safeArrayMap(json['limited_actions'], LimitedActionResultsDataFromJSON),
    };
}

export function TweetLimitedActionResultsToJSON(json: any): TweetLimitedActionResults {
    return TweetLimitedActionResultsToJSONTyped(json, false);
}

export function TweetLimitedActionResultsToJSONTyped(value?: TweetLimitedActionResults | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limited_actions': safeArrayMap(value['limitedActions'], LimitedActionResultsDataToJSON),
    };
}

