/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileBio
 */
export interface UserProfileBio {
    /**
     * 
     * @type {string}
     * @memberof UserProfileBio
     */
    description?: string;
}

/**
 * Check if a given object implements the UserProfileBio interface.
 */
export function instanceOfUserProfileBio(value: object): value is UserProfileBio {
    return true;
}

export function UserProfileBioFromJSON(json: any): UserProfileBio {
    return UserProfileBioFromJSONTyped(json, false);
}

export function UserProfileBioFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileBio {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UserProfileBioToJSON(json: any): UserProfileBio {
    return UserProfileBioToJSONTyped(json, false);
}

export function UserProfileBioToJSONTyped(value?: UserProfileBio | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
    };
}

